Make travis wait up to 40 minutes before killing deploy. Add docs to deploy script

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,6 +1,41 @@
 #! /usr/bin/env bash
 set -e # exit entire script when command exits with non-zero status
 
+usage () {
+    cat <<HELP_USAGE
+
+    HELP
+
+    Deploys mobile applications using expo to the play store
+    and the app stores.
+
+    $ ./deploy environment
+
+    environment: Either "production" or "staging"
+
+    Required environment variables:
+    SENTRY_AUTH_TOKEN: The auth token for sentry
+    EXPO_USERNAME: The Big Neon Expo username
+    EXPO_PASSWORD: The Big Neon Expo password
+    DELIVER_USERNAME: Your Apple developer username
+    DELIVER_PASSWORD: Your Apple developer password
+    FASTLANE_ITC_TEAM_ID: The Big Neon Itunes connect Team ID (119447135)
+
+    Requirements
+HELP_USAGE
+}
+
+if [ "$#" -lt 1 ]; then
+  usage
+  exit 1
+fi
+
+if [ -z "$SENTRY_AUTH_TOKEN" ] || [ -z "$EXPO_USERNAME" ] || [ -z "$EXPO_PASSWORD" ] || [ -z "$DELIVER_USERNAME" ] || [ -z "$DELIVER_PASSWORD" ] || [ -z "$FASTLANE_ITC_TEAM_ID" ]; then
+  echo 'ERROR: Missing required environment variable'
+  usage
+  exit 1
+fi
+
 # Environment should be "production" or "staging"
 ENVIRONMENT=$1
 
@@ -8,31 +43,35 @@ ENVIRONMENT=$1
 TRACK=$([ "$ENVIRONMENT" = "production" ] && echo "beta" || echo "alpha")
 
 # inject sentry auth token into app.json
-[ -z "$SENTRY_AUTH_TOKEN" ] && echo 'Missing required environment vars.' && exit 1
+echo "Injecting SENTRY_AUTH_TOKEN into app.json"
 sed -i .bak "s/__SECRET_SENTRY_AUTH_TOKEN__/$SENTRY_AUTH_TOKEN/g" app.json
 
 # Install dependencies
+echo "Installing dependencies"
 npm ci
 
-# Login to expo
+echo "Logging into Expo as Big Neon"
 npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
 
-# Publish release
+echo "Publishing release to $ENVIRONMENT channel"
 npx expo publish --release-channel $ENVIRONMENT --non-interactive
 
-# Start building standalone android build using release channel
+echo "Starting standalone android build on $ENVIRONMENT channel"
 npx expo build:android --release-channel $ENVIRONMENT --non-interactive --no-publish
 
 # Download the built android binary
+echo "Downloading android apk"
 curl -o app.apk "$(npx expo url:apk --non-interactive)"
 
 # Ask Keith for the JSON key. Store this one directory below the app, and DO NOT ADD TO GIT
+echo "Publishing apk to $TRACK track in Google Play Store"
 fastlane supply --track $TRACK --json_key './.creds/google-deploy-key.json' --package_name "com.bigneon.mobile" --apk "app.apk" --skip_upload_metadata --skip_upload_images --skip_upload_screenshots
 
-# Start building standalone iOS build using release channel
+echo "Starting standalone iOS build on $ENVIRONMENT channel"
 npx expo build:ios --release-channel $ENVIRONMENT --non-interactive --no-publish
 
 # Download the artifact to current directory as `app.ipa`
+echo "Downloading iOS ipa"
 curl -o app.ipa "$(npx expo url:ipa --non-interactive)"
 
 # In your bash profile, you'll need to set:
@@ -41,4 +80,7 @@ curl -o app.ipa "$(npx expo url:ipa --non-interactive)"
 # export FASTLANE_ITC_TEAM_ID=119447135
 
 # Use fastlane to upload your current standalone iOS build to test flight on iTunes Connect.
+echo "Publishing to iTunes Connect"
 fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata --username $DELIVER_USERNAME
+
+echo "$ENVIRONMENT deploy completed"
